server:
  port: 10081
spring:
  application:
    name: food-app-api-gateway
  cloud:
    gateway:
      routes:
        - id: food-app-menu-service
          uri: lb://food-app-menu-service
          predicates:
            - Path=/api/kitchen/**
            - Method=GET,POST,DELETE,PUT,OPTIONS,HEAD
          filters:
            - RemoveRequestHeader=Cookie
        - id: food-app-order-service
          uri: lb://food-app-order-service
          predicates:
            - Path=/api/customer/order/**
            - Method=GET,POST,DELETE,PUT,OPTIONS,HEAD
          filters:
            - RemoveRequestHeader=Cookie
        - id: food-app-user-service
          uri: lb://food-app-user-service
          predicates:
            - Path=/api/user/**
            - Method=GET,POST,DELETE,PUT,OPTIONS,HEAD
          filters:
            - RemoveRequestHeader=Cookie
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:10079/eureka

