server:
  port: 10078
spring:
  application:
    name: food-app-config-server
  cloud:
    config:
      server:
        git:
          uri: 'file:///home/gaurav/Desktop/COURSES/SPRING MICROSERVICES CLOUD/git-localconfig-repo'

          #https://github.com/gauravuq/git-localconfig-repo
